### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by locness3** [mazzlabs/ScratchLib#1]
Allow using this in the browser ;)

**Comment by mazzlabs** [comment]
Thanks for stepping by!
Yes, browser support is planned. However, I don't have a lot of time this week to implement it.
Do you think you can make a PR about it? Thanks a lot!

**Comment by mazzlabs** [comment]
@locness3 also, by browser support we both mean to correct the CORS problem right?

**Comment by locness3** [comment]
Ah yes, didn't thought of that. Why don't the Scratch Team allows all origins though, this apparently was a "temporary problem" 😒

**Comment by mazzlabs** [comment]
Got the problem months ago, and decided to stop the project I was working on because of that... this is honestly dumb. I'll do everything I can, but I think the problem will remain out of my scope.
Thanks for sharing this issue, though!

**Comment by mazzlabs** [comment]
For the moment, I'll just try to set headers to my fetch requests. I don't think it'll work, but still... let's try

**Comment by mazzlabs** [comment]
Didn't work - however module works fine with [browserify](http://browserify.org/). Closing the issue
