### ISSUE TITLE
Allow setting a URL prefix

### ISSUE THREAD

**Issue by locness3** [mazzlabs/ScratchLib#3]
Add an option for a URL prefix to be used in the request URLs, because CORS proxies.

**Comment by mazzlabs** [comment]
As this project isn't maintained anymore I suggest you doing a PR that I can merge in. 
Thanks for the issue!

**Comment by locness3** [comment]
I don't know TypeScript yet. Also you should clearly state that this is unmaintained, I was about to use this.

**Comment by mazzlabs** [comment]
I'll do that.
Can you please link me a mdn doc page to help me implement it? Thanks a lot!

**Comment by mazzlabs** [comment]
Should be good! 😄 <hr>

![image](https://user-images.githubusercontent.com/37367577/96717883-7e0a4300-13a7-11eb-896a-3cc9fc81f266.png)
![image](https://user-images.githubusercontent.com/37367577/96717797-57e4a300-13a7-11eb-8ddb-6d35a8a528e3.png)
<hr>

Closing the issue. Feel free to re-open it if something doesn't work 👍🏻
